/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mlog.engagement.api;

import com.mlog.engagement.model.CommentCreateRequest;
import com.mlog.engagement.model.CommentListResponse;
import com.mlog.engagement.model.CommentResponse;
import com.mlog.engagement.model.CommentUpdateRequest;
import org.springframework.lang.Nullable;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-11T14:36:31.411887001+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "comments", description = "the comments API")
public interface CommentsApi {

    default CommentsApiDelegate getDelegate() {
        return new CommentsApiDelegate() {};
    }

    String PATH_API_V1_COMMENTS_COMMENT_ID_DELETE = "/api/v1/comments/{comment_id}";
    /**
     * DELETE /api/v1/comments/{comment_id} : Soft delete a comment
     *
     * @param commentId  (required)
     * @return Deleted (status code 204)
     */
    @Operation(
        operationId = "apiV1CommentsCommentIdDelete",
        summary = "Soft delete a comment",
        tags = { "comments" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Deleted")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = CommentsApi.PATH_API_V1_COMMENTS_COMMENT_ID_DELETE
    )
    default ResponseEntity<Void> apiV1CommentsCommentIdDelete(
        @NotNull @Parameter(name = "comment_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("comment_id") UUID commentId
    ) {
        return getDelegate().apiV1CommentsCommentIdDelete(commentId);
    }


    String PATH_API_V1_COMMENTS_COMMENT_ID_PUT = "/api/v1/comments/{comment_id}";
    /**
     * PUT /api/v1/comments/{comment_id} : Update comment content
     * User can only edit the content, not the postId or parentId.
     *
     * @param commentId  (required)
     * @param commentUpdateRequest  (required)
     * @return Updated successfully (status code 200)
     *         or Not authorized to edit this comment (status code 403)
     */
    @Operation(
        operationId = "apiV1CommentsCommentIdPut",
        summary = "Update comment content",
        description = "User can only edit the content, not the postId or parentId.",
        tags = { "comments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommentResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Not authorized to edit this comment")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = CommentsApi.PATH_API_V1_COMMENTS_COMMENT_ID_PUT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CommentResponse> apiV1CommentsCommentIdPut(
        @NotNull @Parameter(name = "comment_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("comment_id") UUID commentId,
        @Parameter(name = "CommentUpdateRequest", description = "", required = true) @Valid @RequestBody CommentUpdateRequest commentUpdateRequest
    ) {
        return getDelegate().apiV1CommentsCommentIdPut(commentId, commentUpdateRequest);
    }


    String PATH_API_V1_COMMENTS_COMMENT_ID_REPLIES_GET = "/api/v1/comments/{comment_id}/replies";
    /**
     * GET /api/v1/comments/{comment_id}/replies : Get replies of a comment (Lazy loading)
     *
     * @param commentId  (required)
     * @param cursor  (optional)
     * @param limit  (optional, default to 5)
     * @return List of replies (status code 200)
     */
    @Operation(
        operationId = "apiV1CommentsCommentIdRepliesGet",
        summary = "Get replies of a comment (Lazy loading)",
        tags = { "comments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of replies", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommentListResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CommentsApi.PATH_API_V1_COMMENTS_COMMENT_ID_REPLIES_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<CommentListResponse> apiV1CommentsCommentIdRepliesGet(
        @NotNull @Parameter(name = "comment_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("comment_id") UUID commentId,
        @Parameter(name = "cursor", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "cursor", required = false) @Nullable String cursor,
        @Parameter(name = "limit", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "5") Integer limit
    ) {
        return getDelegate().apiV1CommentsCommentIdRepliesGet(commentId, cursor, limit);
    }


    String PATH_API_V1_COMMENTS_POST = "/api/v1/comments";
    /**
     * POST /api/v1/comments : Create a comment or reply
     * Send &#x60;parentId&#x60; to reply, leave null for root comment.
     *
     * @param commentCreateRequest  (required)
     * @return Comment created (status code 201)
     */
    @Operation(
        operationId = "apiV1CommentsPost",
        summary = "Create a comment or reply",
        description = "Send `parentId` to reply, leave null for root comment.",
        tags = { "comments" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Comment created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommentResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = CommentsApi.PATH_API_V1_COMMENTS_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CommentResponse> apiV1CommentsPost(
        @Parameter(name = "CommentCreateRequest", description = "", required = true) @Valid @RequestBody CommentCreateRequest commentCreateRequest
    ) {
        return getDelegate().apiV1CommentsPost(commentCreateRequest);
    }


    String PATH_API_V1_POSTS_POST_ID_COMMENTS_GET = "/api/v1/posts/{post_id}/comments";
    /**
     * GET /api/v1/posts/{post_id}/comments : Get root comment for a post
     * Fetches only top-level comments (parentId &#x3D; null).  Use &#x60;replyCount&#x60; in response to decide whether to fetch replies. 
     *
     * @param postId  (required)
     * @param cursor ID/Time cursor for pagination (optional)
     * @param limit  (optional, default to 10)
     * @return List of comments (status code 200)
     */
    @Operation(
        operationId = "apiV1PostsPostIdCommentsGet",
        summary = "Get root comment for a post",
        description = "Fetches only top-level comments (parentId = null).  Use `replyCount` in response to decide whether to fetch replies. ",
        tags = { "comments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of comments", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CommentListResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CommentsApi.PATH_API_V1_POSTS_POST_ID_COMMENTS_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<CommentListResponse> apiV1PostsPostIdCommentsGet(
        @NotNull @Parameter(name = "post_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("post_id") Long postId,
        @Parameter(name = "cursor", description = "ID/Time cursor for pagination", in = ParameterIn.QUERY) @Valid @RequestParam(value = "cursor", required = false) @Nullable String cursor,
        @Parameter(name = "limit", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "10") Integer limit
    ) {
        return getDelegate().apiV1PostsPostIdCommentsGet(postId, cursor, limit);
    }

}
