/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mlog.engagement.api;

import org.springframework.lang.Nullable;
import java.util.UUID;
import com.mlog.engagement.model.UserListResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-18T20:05:32.776621850+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "follows", description = "the follows API")
public interface FollowsApi {

    default FollowsApiDelegate getDelegate() {
        return new FollowsApiDelegate() {};
    }

    String PATH_FOLLOW_USER = "/api/v1/users/{target_user_id}/follow";
    /**
     * POST /api/v1/users/{target_user_id}/follow : Follow a user (author)
     * Action: Current logged-in user follows &#x60;target_user_id&#x60;. Use case: Use this when clicking \&quot;Follow\&quot; on a Profile or on a Post (get authorId from post data). 
     *
     * @param targetUserId The ID of the user/author to follow (required)
     * @param xUserinfo A base64-encoded JSON object containing user claims forwarded from the API gateway. After decoding, the JSON will contain user information such as subject (user ID), roles, etc. Example decoded object: &#x60;{\&quot;sub\&quot;: \&quot;user-uuid\&quot;, \&quot;realm_access\&quot;: {\&quot;roles\&quot;: [\&quot;user\&quot;]}, \&quot;email\&quot;: \&quot;user@example.com\&quot;}&#x60; (required)
     * @return Followed successfully (status code 204)
     *         or Cannot follow yourself (status code 400)
     *         or Already following (status code 409)
     */
    @Operation(
        operationId = "followUser",
        summary = "Follow a user (author)",
        description = "Action: Current logged-in user follows `target_user_id`. Use case: Use this when clicking \"Follow\" on a Profile or on a Post (get authorId from post data). ",
        tags = { "follows" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Followed successfully"),
            @ApiResponse(responseCode = "400", description = "Cannot follow yourself"),
            @ApiResponse(responseCode = "409", description = "Already following")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = FollowsApi.PATH_FOLLOW_USER
    )
    default ResponseEntity<Void> followUser(
        @NotNull @Parameter(name = "target_user_id", description = "The ID of the user/author to follow", required = true, in = ParameterIn.PATH) @PathVariable("target_user_id") UUID targetUserId,
        @NotNull @Parameter(name = "X-Userinfo", description = "A base64-encoded JSON object containing user claims forwarded from the API gateway. After decoding, the JSON will contain user information such as subject (user ID), roles, etc. Example decoded object: `{\"sub\": \"user-uuid\", \"realm_access\": {\"roles\": [\"user\"]}, \"email\": \"user@example.com\"}`", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Userinfo", required = true) String xUserinfo
    ) {
        return getDelegate().followUser(targetUserId, xUserinfo);
    }


    String PATH_GET_ALL_FOLLOWERS = "/api/v1/users/{user_id}/followers";
    /**
     * GET /api/v1/users/{user_id}/followers : Get list of followers
     * List of people who are following &#x60;user_id&#x60;.
     *
     * @param userId  (required)
     * @param xUserinfo A base64-encoded JSON object containing user claims forwarded from the API gateway. After decoding, the JSON will contain user information such as subject (user ID), roles, etc. Example decoded object: &#x60;{\&quot;sub\&quot;: \&quot;user-uuid\&quot;, \&quot;realm_access\&quot;: {\&quot;roles\&quot;: [\&quot;user\&quot;]}, \&quot;email\&quot;: \&quot;user@example.com\&quot;}&#x60; (required)
     * @param page  (optional, default to 1)
     * @param limit  (optional, default to 20)
     * @return List of followers (status code 200)
     */
    @Operation(
        operationId = "getAllFollowers",
        summary = "Get list of followers",
        description = "List of people who are following `user_id`.",
        tags = { "follows" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of followers", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserListResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = FollowsApi.PATH_GET_ALL_FOLLOWERS,
        produces = { "application/json" }
    )
    default ResponseEntity<UserListResponse> getAllFollowers(
        @NotNull @Parameter(name = "user_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("user_id") UUID userId,
        @NotNull @Parameter(name = "X-Userinfo", description = "A base64-encoded JSON object containing user claims forwarded from the API gateway. After decoding, the JSON will contain user information such as subject (user ID), roles, etc. Example decoded object: `{\"sub\": \"user-uuid\", \"realm_access\": {\"roles\": [\"user\"]}, \"email\": \"user@example.com\"}`", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Userinfo", required = true) String xUserinfo,
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page,
        @Parameter(name = "limit", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "20") Integer limit
    ) {
        return getDelegate().getAllFollowers(userId, xUserinfo, page, limit);
    }


    String PATH_GET_ALL_FOLLOWING = "/api/v1/users/{user_id}/following";
    /**
     * GET /api/v1/users/{user_id}/following : Get list of following
     * List of people that &#x60;user_id&#x60; is following.
     *
     * @param userId  (required)
     * @param xUserinfo A base64-encoded JSON object containing user claims forwarded from the API gateway. After decoding, the JSON will contain user information such as subject (user ID), roles, etc. Example decoded object: &#x60;{\&quot;sub\&quot;: \&quot;user-uuid\&quot;, \&quot;realm_access\&quot;: {\&quot;roles\&quot;: [\&quot;user\&quot;]}, \&quot;email\&quot;: \&quot;user@example.com\&quot;}&#x60; (required)
     * @param page  (optional, default to 1)
     * @param limit  (optional, default to 20)
     * @return List of people being followed (status code 200)
     */
    @Operation(
        operationId = "getAllFollowing",
        summary = "Get list of following",
        description = "List of people that `user_id` is following.",
        tags = { "follows" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of people being followed", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserListResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = FollowsApi.PATH_GET_ALL_FOLLOWING,
        produces = { "application/json" }
    )
    default ResponseEntity<UserListResponse> getAllFollowing(
        @NotNull @Parameter(name = "user_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("user_id") UUID userId,
        @NotNull @Parameter(name = "X-Userinfo", description = "A base64-encoded JSON object containing user claims forwarded from the API gateway. After decoding, the JSON will contain user information such as subject (user ID), roles, etc. Example decoded object: `{\"sub\": \"user-uuid\", \"realm_access\": {\"roles\": [\"user\"]}, \"email\": \"user@example.com\"}`", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Userinfo", required = true) String xUserinfo,
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page,
        @Parameter(name = "limit", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "20") Integer limit
    ) {
        return getDelegate().getAllFollowing(userId, xUserinfo, page, limit);
    }


    String PATH_UNFOLLOW_USER = "/api/v1/users/{target_user_id}/follow";
    /**
     * DELETE /api/v1/users/{target_user_id}/follow : Unfollow a user
     *
     * @param targetUserId  (required)
     * @param xUserinfo A base64-encoded JSON object containing user claims forwarded from the API gateway. After decoding, the JSON will contain user information such as subject (user ID), roles, etc. Example decoded object: &#x60;{\&quot;sub\&quot;: \&quot;user-uuid\&quot;, \&quot;realm_access\&quot;: {\&quot;roles\&quot;: [\&quot;user\&quot;]}, \&quot;email\&quot;: \&quot;user@example.com\&quot;}&#x60; (required)
     * @return Unfollowed successfully (status code 204)
     */
    @Operation(
        operationId = "unfollowUser",
        summary = "Unfollow a user",
        tags = { "follows" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Unfollowed successfully")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = FollowsApi.PATH_UNFOLLOW_USER
    )
    default ResponseEntity<Void> unfollowUser(
        @NotNull @Parameter(name = "target_user_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("target_user_id") UUID targetUserId,
        @NotNull @Parameter(name = "X-Userinfo", description = "A base64-encoded JSON object containing user claims forwarded from the API gateway. After decoding, the JSON will contain user information such as subject (user ID), roles, etc. Example decoded object: `{\"sub\": \"user-uuid\", \"realm_access\": {\"roles\": [\"user\"]}, \"email\": \"user@example.com\"}`", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Userinfo", required = true) String xUserinfo
    ) {
        return getDelegate().unfollowUser(targetUserId, xUserinfo);
    }

}
