/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mlog.engagement.api;

import org.springframework.lang.Nullable;
import com.mlog.engagement.model.UserListResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-18T07:05:13.042309488+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "likes", description = "the likes API")
public interface LikesApi {

    default LikesApiDelegate getDelegate() {
        return new LikesApiDelegate() {};
    }

    String PATH_GET_ALL_LIKES_OF_POST = "/api/v1/posts/{post_id}/likes";
    /**
     * GET /api/v1/posts/{post_id}/likes : Get list of users who liked the post
     *
     * @param postId  (required)
     * @param xUserinfo A base64-encoded JSON object containing user claims forwarded from the API gateway. After decoding, the JSON will contain user information such as subject (user ID), roles, etc. Example decoded object: &#x60;{\&quot;sub\&quot;: \&quot;user-uuid\&quot;, \&quot;realm_access\&quot;: {\&quot;roles\&quot;: [\&quot;user\&quot;]}, \&quot;email\&quot;: \&quot;user@example.com\&quot;}&#x60; (required)
     * @param page  (optional, default to 1)
     * @param limit  (optional, default to 20)
     * @return List of users who liked the post (status code 200)
     */
    @Operation(
        operationId = "getAllLikesOfPost",
        summary = "Get list of users who liked the post",
        tags = { "likes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of users who liked the post", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserListResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = LikesApi.PATH_GET_ALL_LIKES_OF_POST,
        produces = { "application/json" }
    )
    default ResponseEntity<UserListResponse> getAllLikesOfPost(
        @NotNull @Parameter(name = "post_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("post_id") Long postId,
        @NotNull @Parameter(name = "X-Userinfo", description = "A base64-encoded JSON object containing user claims forwarded from the API gateway. After decoding, the JSON will contain user information such as subject (user ID), roles, etc. Example decoded object: `{\"sub\": \"user-uuid\", \"realm_access\": {\"roles\": [\"user\"]}, \"email\": \"user@example.com\"}`", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Userinfo", required = true) String xUserinfo,
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page,
        @Parameter(name = "limit", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "20") Integer limit
    ) {
        return getDelegate().getAllLikesOfPost(postId, xUserinfo, page, limit);
    }


    String PATH_LIKE_POST = "/api/v1/posts/{post_id}/likes";
    /**
     * POST /api/v1/posts/{post_id}/likes : Like a post
     *
     * @param postId  (required)
     * @param xUserinfo A base64-encoded JSON object containing user claims forwarded from the API gateway. After decoding, the JSON will contain user information such as subject (user ID), roles, etc. Example decoded object: &#x60;{\&quot;sub\&quot;: \&quot;user-uuid\&quot;, \&quot;realm_access\&quot;: {\&quot;roles\&quot;: [\&quot;user\&quot;]}, \&quot;email\&quot;: \&quot;user@example.com\&quot;}&#x60; (required)
     * @return Liked successfully (status code 201)
     *         or Already liked (status code 409)
     */
    @Operation(
        operationId = "likePost",
        summary = "Like a post",
        tags = { "likes" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Liked successfully"),
            @ApiResponse(responseCode = "409", description = "Already liked")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = LikesApi.PATH_LIKE_POST
    )
    default ResponseEntity<Void> likePost(
        @NotNull @Parameter(name = "post_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("post_id") Long postId,
        @NotNull @Parameter(name = "X-Userinfo", description = "A base64-encoded JSON object containing user claims forwarded from the API gateway. After decoding, the JSON will contain user information such as subject (user ID), roles, etc. Example decoded object: `{\"sub\": \"user-uuid\", \"realm_access\": {\"roles\": [\"user\"]}, \"email\": \"user@example.com\"}`", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Userinfo", required = true) String xUserinfo
    ) {
        return getDelegate().likePost(postId, xUserinfo);
    }


    String PATH_UNLIKE_POST = "/api/v1/posts/{post_id}/likes";
    /**
     * DELETE /api/v1/posts/{post_id}/likes : Unlike a post
     *
     * @param postId  (required)
     * @param xUserinfo A base64-encoded JSON object containing user claims forwarded from the API gateway. After decoding, the JSON will contain user information such as subject (user ID), roles, etc. Example decoded object: &#x60;{\&quot;sub\&quot;: \&quot;user-uuid\&quot;, \&quot;realm_access\&quot;: {\&quot;roles\&quot;: [\&quot;user\&quot;]}, \&quot;email\&quot;: \&quot;user@example.com\&quot;}&#x60; (required)
     * @return Unliked successfully (status code 204)
     */
    @Operation(
        operationId = "unlikePost",
        summary = "Unlike a post",
        tags = { "likes" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Unliked successfully")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = LikesApi.PATH_UNLIKE_POST
    )
    default ResponseEntity<Void> unlikePost(
        @NotNull @Parameter(name = "post_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("post_id") Long postId,
        @NotNull @Parameter(name = "X-Userinfo", description = "A base64-encoded JSON object containing user claims forwarded from the API gateway. After decoding, the JSON will contain user information such as subject (user ID), roles, etc. Example decoded object: `{\"sub\": \"user-uuid\", \"realm_access\": {\"roles\": [\"user\"]}, \"email\": \"user@example.com\"}`", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Userinfo", required = true) String xUserinfo
    ) {
        return getDelegate().unlikePost(postId, xUserinfo);
    }

}
