/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mlog.user.api;

import com.mlog.user.model.BanUserRequest;
import java.util.UUID;
import com.mlog.user.model.UnbanUserRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-07T20:19:34.840755520+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "admin", description = "the admin API")
public interface AdminApi {

    default AdminApiDelegate getDelegate() {
        return new AdminApiDelegate() {};
    }

    String PATH_BAN_USER = "/api/v1/admin/users/{user_id}/ban";
    /**
     * POST /api/v1/admin/users/{user_id}/ban : Ban user with user_id
     *
     * @param userId  (required)
     * @param banUserRequest Information about why the user is banned (required)
     * @return User banned successfully (status code 200)
     */
    @Operation(
        operationId = "banUser",
        summary = "Ban user with user_id",
        tags = { "admin" },
        responses = {
            @ApiResponse(responseCode = "200", description = "User banned successfully")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_BAN_USER,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> banUser(
        @NotNull @Parameter(name = "user_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("user_id") UUID userId,
        @Parameter(name = "BanUserRequest", description = "Information about why the user is banned", required = true) @Valid @RequestBody BanUserRequest banUserRequest
    ) {
        return getDelegate().banUser(userId, banUserRequest);
    }


    String PATH_UNBAN_USER = "/api/v1/admin/users/{user_id}/unban";
    /**
     * POST /api/v1/admin/users/{user_id}/unban : Unban user with user_id
     *
     * @param userId  (required)
     * @param unbanUserRequest Informations about why the user is unbanned (required)
     * @return User unbanned successfully (status code 200)
     */
    @Operation(
        operationId = "unbanUser",
        summary = "Unban user with user_id",
        tags = { "admin" },
        responses = {
            @ApiResponse(responseCode = "200", description = "User unbanned successfully")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_UNBAN_USER,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> unbanUser(
        @NotNull @Parameter(name = "user_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("user_id") UUID userId,
        @Parameter(name = "UnbanUserRequest", description = "Informations about why the user is unbanned", required = true) @Valid @RequestBody UnbanUserRequest unbanUserRequest
    ) {
        return getDelegate().unbanUser(userId, unbanUserRequest);
    }

}
