/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.mlog.user.api;

import com.mlog.user.model.ApiV1AuthCallbackGet200Response;
import org.springframework.lang.Nullable;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-04T10:07:53.173542+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "keycloak", description = "the keycloak API")
public interface KeycloakApi {

    default KeycloakApiDelegate getDelegate() {
        return new KeycloakApiDelegate() {};
    }

    String PATH_API_V1_AUTH_CALLBACK_GET = "/api/v1/auth/callback";
    /**
     * GET /api/v1/auth/callback : OAuth2 callback endpoint for Keycloak
     *
     * @param code  (optional)
     * @return Login successful, Session Cookie set (status code 200)
     */
    @Operation(
        operationId = "apiV1AuthCallbackGet",
        summary = "OAuth2 callback endpoint for Keycloak",
        tags = { "keycloak" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Login successful, Session Cookie set", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiV1AuthCallbackGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = KeycloakApi.PATH_API_V1_AUTH_CALLBACK_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<ApiV1AuthCallbackGet200Response> apiV1AuthCallbackGet(
        @Parameter(name = "code", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "code", required = false) @Nullable String code
    ) {
        return getDelegate().apiV1AuthCallbackGet(code);
    }


    String PATH_API_V1_AUTH_GET = "/api/v1/auth";
    /**
     * GET /api/v1/auth : Redirect to Keycloak account management page
     *
     * @return Redirect to Keycloak (status code 302)
     */
    @Operation(
        operationId = "apiV1AuthGet",
        summary = "Redirect to Keycloak account management page",
        tags = { "keycloak" },
        responses = {
            @ApiResponse(responseCode = "302", description = "Redirect to Keycloak")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = KeycloakApi.PATH_API_V1_AUTH_GET
    )
    default ResponseEntity<Void> apiV1AuthGet(
        
    ) {
        return getDelegate().apiV1AuthGet();
    }


    String PATH_API_V1_AUTH_LOGIN_GET = "/api/v1/auth/login";
    /**
     * GET /api/v1/auth/login : Redirect user to Keycloak for login
     *
     * @return Redirect to Keycloak login page (status code 302)
     */
    @Operation(
        operationId = "apiV1AuthLoginGet",
        summary = "Redirect user to Keycloak for login",
        tags = { "keycloak" },
        responses = {
            @ApiResponse(responseCode = "302", description = "Redirect to Keycloak login page")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = KeycloakApi.PATH_API_V1_AUTH_LOGIN_GET
    )
    default ResponseEntity<Void> apiV1AuthLoginGet(
        
    ) {
        return getDelegate().apiV1AuthLoginGet();
    }


    String PATH_API_V1_AUTH_LOGOUT_GET = "/api/v1/auth/logout";
    /**
     * GET /api/v1/auth/logout : Logout user and end Keycloak session
     *
     * @return Redirect to Keycloak logout page (status code 302)
     */
    @Operation(
        operationId = "apiV1AuthLogoutGet",
        summary = "Logout user and end Keycloak session",
        tags = { "keycloak" },
        responses = {
            @ApiResponse(responseCode = "302", description = "Redirect to Keycloak logout page")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = KeycloakApi.PATH_API_V1_AUTH_LOGOUT_GET
    )
    default ResponseEntity<Void> apiV1AuthLogoutGet(
        
    ) {
        return getDelegate().apiV1AuthLogoutGet();
    }


    String PATH_API_V1_AUTH_PASSWORD_RESET_GET = "/api/v1/auth/password/reset";
    /**
     * GET /api/v1/auth/password/reset : Redirect to Keycloak password reset page
     *
     * @return Redirect to Keycloak (status code 302)
     */
    @Operation(
        operationId = "apiV1AuthPasswordResetGet",
        summary = "Redirect to Keycloak password reset page",
        tags = { "keycloak" },
        responses = {
            @ApiResponse(responseCode = "302", description = "Redirect to Keycloak")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = KeycloakApi.PATH_API_V1_AUTH_PASSWORD_RESET_GET
    )
    default ResponseEntity<Void> apiV1AuthPasswordResetGet(
        
    ) {
        return getDelegate().apiV1AuthPasswordResetGet();
    }


    String PATH_API_V1_AUTH_REGISTER_GET = "/api/v1/auth/register";
    /**
     * GET /api/v1/auth/register : Redirect to Keycloak registration page
     *
     * @return Redirect to Keycloak (status code 302)
     */
    @Operation(
        operationId = "apiV1AuthRegisterGet",
        summary = "Redirect to Keycloak registration page",
        tags = { "keycloak" },
        responses = {
            @ApiResponse(responseCode = "302", description = "Redirect to Keycloak")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = KeycloakApi.PATH_API_V1_AUTH_REGISTER_GET
    )
    default ResponseEntity<Void> apiV1AuthRegisterGet(
        
    ) {
        return getDelegate().apiV1AuthRegisterGet();
    }

}
