# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mood.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mood.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmood.proto\"\x1b\n\x0bMoodRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"E\n\x0cMoodResponse\x12\x0c\n\x04mood\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x13\n\x0b\x65xplanation\x18\x03 \x01(\t29\n\x0bMoodService\x12*\n\x0b\x41nalyzeMood\x12\x0c.MoodRequest\x1a\r.MoodResponseB\x19\n\x15\x63om.example.aiserviceP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mood_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.example.aiserviceP\001'
  _globals['_MOODREQUEST']._serialized_start=14
  _globals['_MOODREQUEST']._serialized_end=41
  _globals['_MOODRESPONSE']._serialized_start=43
  _globals['_MOODRESPONSE']._serialized_end=112
  _globals['_MOODSERVICE']._serialized_start=114
  _globals['_MOODSERVICE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
